#
# Autogenerated by Thrift Compiler (0.14.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
import Common.ttypes

from thrift.transport import TTransport
all_structs = []


class ClientPortOffsets(object):
    PORT_DEVICE_MANAGER_SERVER = 0
    PORT_CALLBACK_CLIENT = 1
    PORT_PLUG_IN_OFFSET = 10

    _VALUES_TO_NAMES = {
        0: "PORT_DEVICE_MANAGER_SERVER",
        1: "PORT_CALLBACK_CLIENT",
        10: "PORT_PLUG_IN_OFFSET",
    }

    _NAMES_TO_VALUES = {
        "PORT_DEVICE_MANAGER_SERVER": 0,
        "PORT_CALLBACK_CLIENT": 1,
        "PORT_PLUG_IN_OFFSET": 10,
    }
fix_spec(all_structs)
del all_structs
