#
# Autogenerated by Thrift Compiler (0.14.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
import Common.ttypes

from thrift.transport import TTransport
all_structs = []


class MessageLevel(object):
    INFO = 0
    WARNING = 1
    EXCEPTION = 2
    CRITICAL = 3

    _VALUES_TO_NAMES = {
        0: "INFO",
        1: "WARNING",
        2: "EXCEPTION",
        3: "CRITICAL",
    }

    _NAMES_TO_VALUES = {
        "INFO": 0,
        "WARNING": 1,
        "EXCEPTION": 2,
        "CRITICAL": 3,
    }
fix_spec(all_structs)
del all_structs
